version: "3"
services:
  app:
    build: .
    ports:
      - 8888:80
    volumes:
      - .:/var/www/html/app
    links:
      - pgsql
      - adminer

  pgsql:
    image: postgres:12.1
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret

  adminer:
    image: adminer:4.7.5
    restart: always
    ports:
      - 8080:8080